name: 'Pre-commit Checks'
description: 'Runs all pre-commit hooks'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit run --all-files
      shell: bash
