name: "Trivy Security Scan"
description: "Runs Trivy security scanner"

inputs:
  severity:
    description: "Severity levels to scan for"
    required: false
    default: "CRITICAL,HIGH"

runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: "fs"
        scan-ref: "."
        format: "sarif"
        output: "trivy-results.sarif"
        severity: ${{ inputs.severity }}

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: "trivy-results.sarif"
