name: "ClamAV Virus Scan"
description: "Runs ClamAV virus scanning"

runs:
  using: "composite"
  steps:
    - name: Install ClamAV
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install clamav clamav-daemon
        sudo freshclam
    - name: Run ClamAV scan
      shell: bash
      run: clamscan --recursive --infected .
