name: "Ruff Linter"
description: "Runs Ruff linting"
inputs:
  files:
    description: "Files to check"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - run: |
        pip install ruff
        ruff check ${{ inputs.files }}
      shell: bash
