name: "Python Tests Runner"
description: "Runs Python unit and integration tests with pytest and uploads coverage to Codecov"

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.10"
  test-type:
    description: "Type of tests to run (unit/integration/all)"
    required: false
    default: "all"
  codecov-token:
    description: "Codecov upload token"
    required: true

outputs:
  coverage-percentage:
    description: "Total coverage percentage"
    value: ${{ steps.coverage.outputs.percentage }}
  tests-passed:
    description: "Whether all tests passed"
    value: ${{ steps.run-tests.outputs.success }}

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"
        pip install codecov

    - name: Run tests
      id: run-tests
      shell: bash
      run: |
        case "${{ inputs.test-type }}" in
          "unit")
            TEST_PATH="tests/unit"
            ;;
          "integration")
            TEST_PATH="tests/integration"
            ;;
          *)
            TEST_PATH="tests/unit tests/integration"
            ;;
        esac

        # Add PYTHONPATH to ensure package is importable
        PYTHONPATH=src pytest $TEST_PATH -n auto \
          && echo "success=true" >> $GITHUB_OUTPUT \
          || echo "success=false" >> $GITHUB_OUTPUT

    - name: Upload coverage to Codecov
      shell: bash
      env:
        CODECOV_TOKEN: ${{ inputs.codecov-token }}
      run: |
        codecov -f coverage.xml -t $CODECOV_TOKEN -F ${{ inputs.test-type }}_py${{ inputs.python-version }}
