name: Bandit Security Scan

on:
  # Automatic triggers
  pull_request:
    branches: [main, develop]
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/bandit.yaml"
  push:
    branches: [main, develop]
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/bandit.yaml"

  # Manual trigger
  workflow_dispatch:
    inputs:
      scan_scope:
        description: "Scan scope (all/changed)"
        required: true
        default: "changed"
        type: choice
        options:
          - all
          - changed
      severity_level:
        description: "Minimum severity level"
        required: true
        default: "LOW"
        type: choice
        options:
          - LOW
          - MEDIUM
          - HIGH
      fail_on_findings:
        description: "Fail workflow on findings"
        required: true
        default: true
        type: boolean

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Bandit scan
        id: bandit
        uses: ./.github/actions/security/bandit
        with:
          scan_scope: ${{ github.event.inputs.scan_scope || 'changed' }}
          severity_level: ${{ github.event.inputs.severity_level || 'LOW' }}
          fail_on_findings: ${{ github.event.inputs.fail_on_findings || 'true' }}
          output_format: "sarif"

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.bandit.outputs.report_path }}
        if: always()

      - name: Upload scan results artifact
        uses: actions/upload-artifact@v3
        with:
          name: bandit-results
          path: ${{ steps.bandit.outputs.report_path }}
        if: always()
