name: Manual Security Checks

on:
  workflow_dispatch:
    inputs:
      security_tool:
        description: "Select security tool to run"
        required: true
        type: choice
        options:
          - all
          - semgrep
          - virus-scan
          - bandit
          - trivy
      severity_level:
        description: "Severity level for Trivy (comma-separated)"
        required: false
        default: "CRITICAL,HIGH"
        type: string
      python_version:
        description: "Python version for Bandit"
        required: false
        default: "3.10"
        type: string

jobs:
  semgrep:
    name: Semgrep Security Scan
    if: inputs.security_tool == 'semgrep' || inputs.security_tool == 'all'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/static-analysis/semgrep
        with:
          publish_token: ${{ secrets.SEMGREP_APP_TOKEN }}

  virus-scan:
    name: ClamAV Virus Scan
    if: inputs.security_tool == 'virus-scan' || inputs.security_tool == 'all'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/security/clamav

  bandit:
    name: Bandit Security Scan
    if: inputs.security_tool == 'bandit' || inputs.security_tool == 'all'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/security/bandit
        with:
          python-version: ${{ inputs.python_version }}

  trivy:
    name: Trivy Security Scan
    if: inputs.security_tool == 'trivy' || inputs.security_tool == 'all'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/security/trivy
        with:
          severity: ${{ inputs.severity_level }}

  summary:
    name: Security Checks Summary
    needs: [semgrep, virus-scan, bandit, trivy]
    runs-on: ubuntu-latest
    if: always() && (needs.semgrep.result != 'skipped' || needs.virus-scan.result != 'skipped' || needs.bandit.result != 'skipped' || needs.trivy.result != 'skipped')
    steps:
      - name: Check job status
        run: |
          echo "Security Scan Summary:"

          # Function to print status
          print_status() {
            local tool=$1
            local result=$2

            if [[ "$result" == "success" ]]; then
              echo "✅ $tool: Passed"
            elif [[ "$result" == "failure" ]]; then
              echo "❌ $tool: Failed"
            elif [[ "$result" == "skipped" ]]; then
              echo "⏭️ $tool: Skipped"
            else
              echo "❓ $tool: Unknown status"
            fi
          }

          print_status "Semgrep" "${{ needs.semgrep.result }}"
          print_status "Virus Scan" "${{ needs.virus-scan.result }}"
          print_status "Bandit" "${{ needs.bandit.result }}"
          print_status "Trivy" "${{ needs.trivy.result }}"

          # Check if any enabled job failed
          for result in "${{ needs.semgrep.result }}" "${{ needs.virus-scan.result }}" "${{ needs.bandit.result }}" "${{ needs.trivy.result }}"; do
            if [[ "$result" == "failure" ]]; then
              echo "⚠️ One or more security checks failed!"
              exit 1
            fi
          done

          echo "✅ All executed security checks passed!"
