name: Pull Request Checks

on:
  pull_request:
    branches: [main, feature]

jobs:
  pre-commit-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linting/pre-commit
