name: Pull Request Checks

on:
  pull_request:
    branches: [main, feature]

jobs:
  pre-commit-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linting/pre-commit
        with:
          files: "."

  ruff-changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linting/ruff
        with:
          files: ${{ join(github.event.pull_request.changed_files, ' ') }}

  bandit-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/security/bandit
        with:
          files: "." # Optional: can add files parameter if you want to scope it
