name: Security Scan
on:
  workflow_dispatch:
    inputs:
      severity:
        description: "Minimum severity level"
        required: true
        default: "HIGH,CRITICAL"
        type: choice
        options:
          - CRITICAL
          - HIGH,CRITICAL
          - MEDIUM,HIGH,CRITICAL
          - LOW,MEDIUM,HIGH,CRITICAL
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master
      - develop
      - "feature/**"
      - "release/**"
  push:
    branches:
      - main
      - master
      - develop
      - "feature/**"
      - "release/**"
  schedule:
    - cron: "0 0 * * 0" # Weekly scan on Sundays

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Combined vulnerability and secret scanning
      - name: Run Trivy filesystem scan
        id: trivy-fs
        uses: ./.github/actions/security/trivy
        with:
          scan_type: fs
          scanners: vuln,secret
          severity: ${{ inputs.severity || 'MEDIUM,HIGH,CRITICAL' }}
          scan_target: "."

      # IaC and misconfiguration scanning
      - name: Run Trivy config scan
        id: trivy-config
        uses: ./.github/actions/security/trivy
        with:
          scan_type: config
          misconfig_scanners: azure-arm,cloudformation,dockerfile,helm,kubernetes,terraform,terraformplan
          scan_target: "."

      # Upload all SARIF files
      - name: Upload SARIF files to Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports
          category: trivy

      # Archive all reports
      - name: Upload scan artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: reports/
          retention-days: 5
